spring.application.name=app

server.port=80

spring.profiles.include=dev,test,private,cloud

#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521/xe
#spring.datasource.username=C##KH
#spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgreskh

#JPA
logging.level.org.hibernate.SQL=DEBUG
# ??? ???? ?? (????? 3 ??)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ???? ???? ???? (?? ???? ??? ??/??)
#spring.jpa.hibernate.ddl-auto=update

# ?????? ?? ??? ???? ?? ?? (??: ?? ???? ??)
# spring.jpa.hibernate.ddl-auto=create

# ?????? ?? ? ??? ??
# spring.jpa.hibernate.ddl-auto=create-drop

# ???? ???? ?? ??? ?? ??
spring.jpa.hibernate.ddl-auto=validate

